name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "Dockerfile"
      - "requirements.txt"
      - ".env*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: main # main 브랜치 명시적 체크아웃

      # 2. Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags:
            ${{ secrets.DOCKER_USERNAME }}/newdawn:latest

      # 5. Helm values.yaml 파일 업데이트
      - name: Update Helm Chart Image Tag
        run: |
          sed -i "s|tag: .*|tag: '${{ github.sha }}'|" Chart/newdawn/values.yaml